[project]
name = "njoy2016"
version = "2016.78.0"
description = "The NJOY Nuclear Data Processing System"
readme = "README.md"
requires-python = ">=3.11.4"
dependencies = []

[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
cmake.args = ["-DCMAKE_BUILD_TYPE=Release"]

[tool.cibuildwheel.linux]
environment = { "CMAKE_ARGS" = "-DCMAKE_BUILD_TYPE=Release -Dstatic_libraries=ON -Dstatic_njoy=ON -DCMAKE_BUILD_TYPE=Release" }

[tool.cibuildwheel.macos]
environment = { "FC" = "/opt/homebrew/bin/gfortran-14", "CMAKE_ARGS" = "-DCMAKE_BUILD_TYPE=Release -Dstatic_libraries=ON -Dstatic_njoy=ON", "MACOSX_DEPLOYMENT_TARGET"="$(sw_vers -productVersion | cut -d '.' -f 1).0"}
