name: Build NJOY2016

on:
  push:
    branches: [python]

jobs:
  build:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Build Wheels
        uses: pypa/cibuildwheel@v2.23.2
